language: python
python: 2.7
sudo: false

# note: python3.5 is not preinstalled on docker-based (i.e. sudo: false)
#       Travis workers at the moment of this writing, so we need to get
#       it via addon repository.
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
      - python3.6
      - python3.6-dev

env:

  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py27-django111

  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django110
  - TOX_ENV=py34-django111

  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=py35-django110
  - TOX_ENV=py35-django111

  - TOX_ENV=py36-django111

  - TOX_ENV=coverage
install:
  # note: pip>=8.0.0 does not work on Python 3.2 but we want to test on py32
  # note: virtualenv>=14.0.0 bundles newer version of pip that does not work on
  #       py32
  - pip install -U 'tox==2.2.1' 'pip<8.0.0' 'virtualenv<14.0.0'
script:
  - tox -e $TOX_ENV
