language: python
python: 2.7
sudo: false

# note: python3.5 is not preinstalled on docker-based (i.e. sudo: false)
#       Travis workers at the moment of this writing, so we need to get
#       it via addon repository.
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
      - python3.6
      - python3.6-dev

env:

  - TOX_ENV=py27-django111

  - TOX_ENV=py34-django111
  - TOX_ENV=py34-django20

  - TOX_ENV=py35-django111
  - TOX_ENV=py35-django20

  - TOX_ENV=py36-django111
  - TOX_ENV=py36-django20

  - TOX_ENV=coverage
install:
  - pip install -U 'tox==2.9.1'
script:
  - tox -e $TOX_ENV
